/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/common/app-main.vue')['default']
    AppSearch: typeof import('./src/components/common/app-search.vue')['default']
    AppTable: typeof import('./src/components/common/app-table.vue')['default']
    AppWithSidebar: typeof import('./src/components/common/app-with-sidebar.vue')['default']
    Com403: typeof import('./src/components/common/errors/com-403.vue')['default']
    Com404: typeof import('./src/components/common/errors/com-404.vue')['default']
    Com404Bg: typeof import('./src/components/common/errors/com-404-bg.vue')['default']
    Com429: typeof import('./src/components/common/errors/com-429.vue')['default']
    Com500: typeof import('./src/components/common/errors/com-500.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormItem: typeof import('./src/components/forms/form-item.vue')['default']
    FormModal: typeof import('./src/components/biz/form-modal/index.vue')['default']
    Logo: typeof import('./src/components/common/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaberButton: typeof import('./src/components/common/saber-button.vue')['default']
    SaberCheckbox: typeof import('./src/components/forms/saber-checkbox.vue')['default']
    SaberDialog: typeof import('./src/components/common/saber-dialog.vue')['default']
    SaberDrawer: typeof import('./src/components/common/saber-drawer.vue')['default']
    SaberEmpty: typeof import('./src/components/common/saber-empty.vue')['default']
    SaberInfo: typeof import('./src/components/common/saber-info/saber-info.vue')['default']
    SaberInfoProvider: typeof import('./src/components/common/saber-info/saber-info-provider.vue')['default']
    SaberRadios: typeof import('./src/components/forms/saber-radios.vue')['default']
    SaberStatus: typeof import('./src/components/common/saber-status.vue')['default']
    SaberTabLayout: typeof import('./src/components/common/saber-tab-layout.vue')['default']
    UmoEditor: typeof import('./src/components/forms/umo-editor.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
